use_frameworks!

platform :ios, '9.0'
source' https://github.com/CocoaPods/Specs.git'

target 'componentTest_Example' do
  pod 'componentTest', :path => '../'

  target 'componentTest_Tests' do
    inherit! :search_paths

    pod 'Cache'
  end
end
